[
    {
        "class": "org.apache.commons.math3.exception.util.ExceptionContext",
        "line": 176,
        "suspicious": 0.47140
    }
]